# api/wrangler.toml
name = "farm2door-api"
main = "src/index.ts"
compatibility_date = "2025-08-30"
compatibility_flags = ["nodejs_compat"]
minify = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "farm2door"
database_id = "285fa696-54ae-4a89-8601-76357392e819"

# Environment variables
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
JWT_REFRESH_SECRET = "your-super-secret-refresh-key-change-in-production"
JWT_EXPIRES_IN = "1h"
JWT_REFRESH_EXPIRES_IN = "30d"
FRONTEND_URL = "http://localhost:3000"

# Production environment variables (set via wrangler secret)
# GOOGLE_CLIENT_ID = "..." (use: wrangler secret put GOOGLE_CLIENT_ID)
# GOOGLE_CLIENT_SECRET = "..." (use: wrangler secret put GOOGLE_CLIENT_SECRET)
# MICROSOFT_CLIENT_ID = "..." (use: wrangler secret put MICROSOFT_CLIENT_ID)
# MICROSOFT_CLIENT_SECRET = "..." (use: wrangler secret put MICROSOFT_CLIENT_SECRET)